# Generated by Django 5.2.15 on 2026-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_slide_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='mpp_source',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='mpp_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
